import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { assertFinancialLedgerContract, assertFinancialLedgerPrecheck, financialLedgerContractHash, FINANCIAL_LEDGER_CONTRACT_SQL, FINANCIAL_LEDGER_CONTRACT_VERSION, materializeFinancialLedgerMigration } from "../scripts/migration-contracts.mjs";
import { inspectFinancialLedgerContract } from "../scripts/migration-safety.mjs";

const sql=await readFile(new URL("../migrations/0005_workspace_financial_ledger.sql",import.meta.url),"utf8"), normalized=sql.replace(/\s+/g," ").trim(), hash=financialLedgerContractHash(sql);
const complete={contract_version:FINANCIAL_LEDGER_CONTRACT_VERSION,contract_hash:hash,object_count:5,has_tables:true,columns_match:true,column_counts_match:true,numeric_shapes_match:true,pks_match:true,fk_match:true,checks_match:true,indexes_match:true,claim_match:true,advance_match:true,acl_tables_closed:true,acl_functions_closed:true,runtime_acl_match:true,rls_enabled:true,policies_match:true,runtime_role_safe:true,no_public_policies:true};

test("0005 permanece aditiva, idempotente e forward-only",()=>{assert.match(normalized,/CREATE TABLE IF NOT EXISTS workspace_financial_transactions/i);assert.doesNotMatch(normalized,/\b(DROP|TRUNCATE)\b|DELETE\s+FROM|UPDATE\s+workspace_channel_/i);assert.match(normalized,/DEFERRABLE INITIALLY DEFERRED NOT VALID/i);});
test("hash vem dos bytes canonicos e detecta drift",()=>{assert.match(hash,/^sha256:[a-f0-9]{64}$/);assert.match(materializeFinancialLedgerMigration(sql,hash),new RegExp(hash));assert.notEqual(financialLedgerContractHash(`${sql}\n-- drift`),hash);assert.throws(()=>materializeFinancialLedgerMigration(`${sql}\n-- drift`,hash),/nao corresponde/);});
test("catalogo read-only cobre contrato DBA completo",()=>{for(const term of ["information_schema.columns","pg_constraint","pg_index","indpred","pg_proc","prosecdef","table_privileges","routine_privileges","pg_policies","relrowsecurity"])assert.match(FINANCIAL_LEDGER_CONTRACT_SQL,new RegExp(term));const withoutLiterals=FINANCIAL_LEDGER_CONTRACT_SQL.replace(/'[^']*'/g,"''");assert.doesNotMatch(withoutLiterals,/\b(CREATE|ALTER|DROP|INSERT|UPDATE|DELETE|GRANT|REVOKE)\b/i);});
test("precheck aceita vazio/reaplicacao e bloqueia preexistente incompatível",()=>{assert.doesNotThrow(()=>assertFinancialLedgerPrecheck({object_count:0}));assert.doesNotThrow(()=>assertFinancialLedgerPrecheck(complete));assert.throws(()=>assertFinancialLedgerPrecheck({...complete,fk_match:false}),/IF NOT EXISTS/);});
test("postcheck exige hash, FK, ACL, RLS e fence",()=>{assert.doesNotThrow(()=>assertFinancialLedgerContract(complete,hash));for(const key of ["fk_match","acl_tables_closed","rls_enabled","claim_match","advance_match"])assert.throws(()=>assertFinancialLedgerContract({...complete,[key]:false},hash),/SCHEMA_BLOCKED/);assert.throws(()=>assertFinancialLedgerContract({...complete,contract_hash:"sha256:bad"},hash),/SCHEMA_BLOCKED/);});
test("fake catalog completo passa e drift/metadata ausente ficam SCHEMA_BLOCKED",async()=>{const inspect=async(body,shape={has_table:true,has_hash:true},metadata={contract_version:FINANCIAL_LEDGER_CONTRACT_VERSION,contract_hash:hash})=>{const seen=[];const responses=[{rowCount:1,rows:[body]},{rowCount:1,rows:[shape]},...(shape.has_table&&shape.has_hash?[{rowCount:1,rows:[metadata]}]:[])];const got=await inspectFinancialLedgerContract(async(q)=>{seen.push(q);const next=responses.shift();assert.ok(next,`query inesperada: ${q}`);return next;},FINANCIAL_LEDGER_CONTRACT_SQL);assert.equal(responses.length,0);assert.ok(seen.every(q=>/^\s*(WITH|SELECT)\b/i.test(q)));return got;};const valid=await inspect(complete);assert.doesNotThrow(()=>assertFinancialLedgerContract(valid,hash));const drift=await inspect({...complete,indexes_match:false});assert.throws(()=>assertFinancialLedgerContract(drift,hash),/SCHEMA_BLOCKED/);const missing=await inspect(complete,{has_table:false,has_hash:false});assert.throws(()=>assertFinancialLedgerContract(missing,hash),/SCHEMA_BLOCKED/);});
test("runtime usa a inspeccao completa com metadata, nao assert sobre query parcial",async()=>{const runtime=await readFile(new URL("../src/lib/db.ts",import.meta.url),"utf8");assert.match(runtime,/inspectFinancialLedgerContract\(/);assert.match(runtime,/assertFinancialLedgerContract\(contract,/);assert.doesNotMatch(runtime,/assertFinancialLedgerContract\(contract\.rows\[0\]/);});
test("0005 nao bloqueia queries gerais e permanece certificada no gate financeiro",async()=>{const runtime=await readFile(new URL("../src/lib/db.ts",import.meta.url),"utf8");const general=runtime.slice(runtime.indexOf("function ensureSchema"),runtime.indexOf("export function ensureFinancialLedgerSchema"));assert.doesNotMatch(general,/FINANCIAL_LEDGER_CONTRACT|0005_workspace_financial_ledger/);const financial=runtime.slice(runtime.indexOf("export function ensureFinancialLedgerSchema"),runtime.indexOf("export async function dbQuery"));assert.match(financial,/inspectFinancialLedgerContract/);assert.match(financial,/SCHEMA_BLOCKED/);const modules=await readFile(new URL("../src/lib/integrations/tiktokModules.ts",import.meta.url),"utf8");assert.match(modules,/readFinance[\s\S]*ensureFinancialLedgerSchema\(\)/);});
test("RLS Supabase fecha roles publicas e role runtime e parametrica",()=>{assert.match(normalized,/ENABLE ROW LEVEL SECURITY/i);assert.match(normalized,/current_setting\('sellercore\.runtime_role'/i);assert.match(normalized,/rolbypassrls/i);assert.doesNotMatch(normalized,/GRANT .+ TO (service_role|anon|authenticated)/i);});
test("proveniencia impede estimativa e settlement contraditorios sem fechar tipos de provider",()=>{assert.match(normalized,/financial_transactions_provenance_check[\s\S]*settlement_state = 'unsettled'[\s\S]*is_estimated[\s\S]*source_rank < 100/i);assert.match(normalized,/settlement_state IN \('settled', 'reversed'\)[\s\S]*NOT is_estimated[\s\S]*source_rank = 100/i);assert.match(normalized,/financial_transactions_statement_source_check[\s\S]*statement_id IS NOT NULL/i);assert.match(normalized,/financial_transactions_pending_source_check[\s\S]*statement_id IS NULL/i);assert.doesNotMatch(normalized,/source_resource\s+IN\s*\(/i);});
test("pagamentos continuam separados e nao viram componentes economicos",()=>{const payments=normalized.slice(normalized.indexOf("CREATE TABLE IF NOT EXISTS workspace_financial_payments"),normalized.indexOf("CREATE TABLE IF NOT EXISTS workspace_financial_sync_checkpoints"));assert.doesNotMatch(payments,/revenue|commission|refunds|profit/i);assert.match(payments,/NOT is_estimated OR paid_at IS NULL/i);});
test("ledger e certificado integralmente sem DDL de autorreparo",async()=>{const runner=await readFile(new URL("../scripts/migrate-cli.mjs",import.meta.url),"utf8");assert.doesNotMatch(normalized,/INSERT INTO migration_contract_versions|INSERT INTO schema_migrations/i);assert.doesNotMatch(runner,/ALTER TABLE migration_contract_versions/i);assert.ok(runner.indexOf("INSERT INTO migration_contract_versions")<runner.indexOf("assertFinancialLedgerContract(certified"));assert.ok(runner.indexOf("assertFinancialLedgerContract(certified")<runner.indexOf("INSERT INTO schema_migrations"));assert.match(runner,/ROLLBACK/);});
test("policy divergente falha antes de ser preservada",()=>{assert.match(normalized,/policy financial_transactions_runtime preexistente diverge/i);assert.match(normalized,/roles=ARRAY\[runtime_role\]/i);assert.match(normalized,/cmd='ALL'/i);});
test("checkpoint persiste apenas hashes SHA-256 bounded e contrato detecta drift",()=>{assert.match(normalized,/cursor_hash_history JSONB NOT NULL DEFAULT '\[\]'::jsonb/i);assert.match(normalized,/\$\.size\(\) <= 256/i);assert.match(normalized,/\^\[0-9a-f\]\{64\}\$/i);assert.doesNotMatch(normalized,/cursor_token_history|seen_cursor_tokens/i);assert.match(FINANCIAL_LEDGER_CONTRACT_SQL,/cursor_hash_history/);assert.match(FINANCIAL_LEDGER_CONTRACT_SQL,/p_cursor_sha256 bytea/);});
