import { NextResponse } from "next/server";
import { getCosts, setCost } from "@/lib/costStore";
import { withAuthenticatedWorkspace } from "@/lib/workspaceContext";
import { readCatalog, requireTiktokConnection, TiktokModuleError } from "@/lib/integrations/tiktokModules";
import { tiktokCostId } from "@/lib/integrations/tiktokContract";
import { invalidateCostDerivedCaches } from "@/lib/costInvalidation";
export const runtime="nodejs"; export const dynamic="force-dynamic";

export async function GET(request:Request){return withAuthenticatedWorkspace(async()=>{try{const params=new URL(request.url).searchParams;const connection=await requireTiktokConnection(params);const [catalog,costs]=await Promise.all([readCatalog(connection,params),getCosts()]);const items=catalog.items.map(product=>{const id=tiktokCostId(connection.id,product.productId,product.sku);const entry=costs[id];return {...product,id,cost:entry?.cost??null,costUpdatedAt:entry?.updatedAt??null};});return NextResponse.json({connection:{id:connection.id},costs:items,page:catalog.page,atividade:catalog.atividade,ocultados:catalog.ocultados,totalNoCanal:catalog.totalNoCanal,availability:catalog.availability});}catch(e){if(e instanceof TiktokModuleError)return NextResponse.json({error:e.message,code:e.code},{status:e.status});return NextResponse.json({error:"Não foi possível carregar custos.",code:"TIKTOK_COSTS_FAILED"},{status:500});}});}
export async function POST(request:Request){return withAuthenticatedWorkspace(async()=>{try{const params=new URL(request.url).searchParams;const connection=await requireTiktokConnection(params);const body=await request.json() as Record<string,unknown>;const productId=typeof body.productId==="string"?body.productId.trim():"";const sku=typeof body.sku==="string"?body.sku.trim():null;const cost=typeof body.cost==="number"?body.cost:Number.NaN;if(!productId||productId.length>160||sku&&sku.length>160||!Number.isFinite(cost)||cost<0)return NextResponse.json({error:"Produto, SKU ou custo inválido.",code:"INVALID_COST"},{status:400});const entry=await setCost({id:tiktokCostId(connection.id,productId,sku),sku:sku??undefined,asin:undefined,title:typeof body.title==="string"?body.title.slice(0,300):undefined,cost});await invalidateCostDerivedCaches();return NextResponse.json({entry});}catch(e){if(e instanceof TiktokModuleError)return NextResponse.json({error:e.message,code:e.code},{status:e.status});return NextResponse.json({error:"Não foi possível salvar o custo.",code:"TIKTOK_COSTS_FAILED"},{status:500});}});}
