"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { EmptyState } from "./EmptyState"; import { DashboardSkeleton } from "./LoadingState"; import { PageHeader } from "./PageHeader";
import { DashboardPeriodFilter, useDashboardPeriod } from "./DashboardPeriodFilter";
import { moduleApiQuery, moduleConnectionHref, moduleError, moduleHref, moduleMoney, updatedModuleQuery } from "./TikTokModulesModel";
import { TIKTOK_CATALOG_STATUSES } from "@/lib/integrations/tiktokModuleContract";

type Kind="monitor"|"finance"|"catalog"|"inventory"|"costs"|"abc";
type Connection={id:string;displayName?:string;externalAccountId?:string};
type ProviderIssue={status:"attention";code:"OWNERSHIP_CONFLICT"|"PROVIDER_READ_FAILED";message:string};
type FinanceCoverage={status?:"complete"|"partial"|"blocked";terminal?:boolean;from?:string;to?:string;source?:"statement_ledger"|"per_order_fallback"|"schema_blocked";estimatesIncluded?:false;rejected?:number};
type Payload={items?:Record<string,unknown>[];costs?:Record<string,unknown>[];availability?:string;page?:{limit:number;offset:number;total:number|null;hasMore:boolean};coverage?:FinanceCoverage|null;profitSubset?:{reason?:string};code?:string;error?:string};
const config:Record<Kind,{title:string;subtitle:string;endpoint:string;period:boolean}>={monitor:{title:"Monitor da conta",subtitle:"Pedidos e estado de conciliação, sem dados pessoais do comprador.",endpoint:"monitor",period:true},finance:{title:"Financeiro",subtitle:"Transações finais do ledger e cobertura dos extratos, sem estimativas.",endpoint:"finance",period:true},catalog:{title:"Anúncios",subtitle:"Catálogo publicado e variações em modo somente leitura.",endpoint:"catalog",period:false},inventory:{title:"Radar de estoque",subtitle:"Cobertura e risco de ruptura, sem projetar quando falta base de venda.",endpoint:"inventory",period:true},costs:{title:"Produtos",subtitle:"Custos por SKU exclusivos desta loja TikTok Shop.",endpoint:"costs",period:false},abc:{title:"Curva ABC",subtitle:"Receita por produto e participação acumulada no período.",endpoint:"abc",period:true}};
const text=(v:unknown)=>v==null||v===""?"—":String(v);

export function TikTokModulePage({kind}:{kind:Kind}) { const cfg=config[kind], router=useRouter(), sp=useSearchParams(); const update=useCallback((values:Record<string,string|null>)=>{router.push(`${location.pathname}?${updatedModuleQuery(sp.toString(),values)}`,{scroll:false})},[router,sp]); const syncPeriod=useCallback((query:string)=>{const source=new URLSearchParams(query);if(source.has("from")&&source.has("to")){update({from:source.get("from"),to:source.get("to")});return}const days=source.get("days")??"30",to=new Date(),from=new Date(to);if(days!=="today")from.setDate(from.getDate()-Math.max(0,Number(days)-1));const iso=(date:Date)=>date.toISOString().slice(0,10);update({from:iso(from),to:iso(to)})},[update]); const period=useDashboardPeriod(sp.toString(),cfg.period?syncPeriod:undefined); const [connections,setConnections]=useState<Connection[]|null>(null); const [providerIssue,setProviderIssue]=useState<ProviderIssue|null>(null); const [data,setData]=useState<{id:string;body:Payload}|null>(null); const [error,setError]=useState(""); const [attempt,setAttempt]=useState(0); const requested=sp.get("connection_id");
  useEffect(()=>{let live=true;fetch("/api/integrations",{cache:"no-store"}).then(r=>r.json().then(b=>{if(!r.ok)throw Error();return b})).then(b=>{const p=b.providers?.find((x:{id:string})=>x.id==="tiktok_shop");if(live){setConnections((p?.connections??[]).slice().sort((a:Connection,b:Connection)=>a.id.localeCompare(b.id)));setProviderIssue(p?.issue??null)}}).catch(()=>live&&setError("Não foi possível carregar as conexões."));return()=>{live=false}},[attempt]);
  const selected=connections?.find(c=>c.id===requested)??connections?.[0]??null;
  useEffect(()=>{if(selected&&requested!==selected.id)router.replace(moduleHref(location.pathname,sp.toString(),selected.id),{scroll:false})},[requested,router,selected,sp]);
  const query=useMemo(()=>selected?moduleApiQuery(sp.toString(),selected.id,kind):"",[kind,selected,sp]);
  // Clear the previous connection synchronously so its data can never flash under a new store selector.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{if(!selected)return;let live=true;setData(null);setError("");fetch(`/api/integrations/tiktok/${cfg.endpoint}?${query}`,{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(moduleError(b.code)||b.error||"Não foi possível carregar este módulo.");return b}).then(body=>live&&setData({id:selected.id,body})).catch(e=>live&&setError(e.message));return()=>{live=false}},[attempt,cfg.endpoint,query,selected]);
  const retry=useCallback(()=>setAttempt(x=>x+1),[]); const body=data&&data.id===selected?.id?data.body:null;
  return <><PageHeader eyebrow="TikTok Shop" title={cfg.title} subtitle={cfg.subtitle} action={selected&&connections&&<label className="flex min-w-52 flex-col gap-1 text-xs font-semibold text-slate-500">Loja<select aria-label="Loja TikTok Shop" className="min-h-11 rounded-lg bg-white px-3 text-base shadow-[inset_0_0_0_1px_rgb(203_213_225)] focus:outline-none focus:ring-2 focus:ring-[var(--channel-accent)] sm:text-sm" value={selected.id} onChange={e=>router.push(moduleConnectionHref(location.pathname,sp.toString(),e.target.value),{scroll:false})}>{connections.map(c=><option key={c.id} value={c.id}>{c.displayName||c.externalAccountId||c.id}</option>)}</select></label>}/>
    {cfg.period&&<DashboardPeriodFilter {...period.filterProps}/>} 
    {!connections&&!error?<DashboardSkeleton/>:providerIssue?<EmptyState kind="permission" title={providerIssue.code==="OWNERSHIP_CONFLICT"?"Conexão TikTok protegida":"Canal TikTok requer atenção"} description={providerIssue.message} action={<Link className="meli-primary-action" href="/integracoes">Gerenciar conexões</Link>}/>:connections?.length===0?<EmptyState title="Nenhuma loja TikTok Shop conectada" description="Conecte uma loja para acessar este módulo." action={<Link className="meli-primary-action" href="/integracoes">Gerenciar conexões</Link>}/>:error?<EmptyState kind="permission" title="Não foi possível carregar" description={error} action={<button className="meli-primary-action min-h-11" onClick={retry}>Tentar novamente</button>}/>:!body?<DashboardSkeleton/>:body.availability==="BLOCKED"?<EmptyState kind="permission" title="Financeiro aguardando estrutura de dados" description="O ledger financeiro ainda não está disponível neste ambiente. Nenhum valor foi estimado ou convertido em zero."/>:body.availability==="NOT_AVAILABLE"?<EmptyState title="Dados ainda indisponíveis" description="A conexão existe, mas este conjunto de dados ainda não foi materializado."/>:<ModuleContent kind={kind} body={body} sp={sp} update={update} retry={retry}/>}</>;
}

function Filters({kind,sp,update}:{kind:Kind;sp:URLSearchParams;update:(v:Record<string,string|null>)=>void}) {
  const [q,setQ]=useState(sp.get("q")??""), [orderId,setOrderId]=useState(sp.get("order_id")??""), [sku,setSku]=useState(sp.get("sku")??"");
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{setQ(sp.get("q")??"");setOrderId(sp.get("order_id")??"");setSku(sp.get("sku")??"")},[sp]);
  const status=sp.get("status")??"";
  const submit=(e:React.FormEvent)=>{e.preventDefault();update(kind==="monitor"?{order_id:orderId||null,sku:sku||null}:{q:q||null})};
  return <form className="mb-5 flex flex-wrap items-end gap-3" onSubmit={submit}>
    {["catalog","inventory","costs"].includes(kind)&&<label className="flex min-w-60 flex-1 flex-col gap-1 text-sm font-medium text-slate-700"><span>Buscar</span><input className="min-h-11 rounded-lg px-3 text-base shadow-[inset_0_0_0_1px_rgb(203_213_225)] focus:ring-2 focus:ring-[var(--channel-accent)] sm:text-sm" value={q} onChange={e=>setQ(e.target.value)} placeholder="Produto, SKU ou ID"/></label>}
    {kind==="monitor"&&<><label className="flex min-w-52 flex-1 flex-col gap-1 text-sm font-medium text-slate-700"><span>Pedido</span><input className="min-h-11 rounded-lg px-3" value={orderId} onChange={e=>setOrderId(e.target.value)} placeholder="ID exato do pedido"/></label><label className="flex min-w-44 flex-1 flex-col gap-1 text-sm font-medium text-slate-700"><span>SKU</span><input className="min-h-11 rounded-lg px-3" value={sku} onChange={e=>setSku(e.target.value)} placeholder="SKU exato"/></label></>}
    {["monitor","catalog"].includes(kind)&&<label className="flex flex-col gap-1 text-sm font-medium text-slate-700"><span>Status</span><select className="min-h-11 rounded-lg px-3" value={status} onChange={e=>update({status:e.target.value||null})}><option value="">Todos</option>{(kind==="monitor"?["pending","paid","shipped","delivered","cancelled"]:TIKTOK_CATALOG_STATUSES).map(value=><option key={value} value={value}>{value}</option>)}</select></label>}
    {kind==="inventory"&&<label className="flex flex-col gap-1 text-sm font-medium text-slate-700"><span>Situação</span><select className="min-h-11 rounded-lg px-3" value={sp.get("filter")??""} onChange={e=>update({filter:e.target.value||null})}><option value="">Todos</option><option value="out">Sem estoque</option><option value="low">Estoque baixo</option><option value="no_sales">Sem vendas</option></select></label>}
    {["monitor","catalog","inventory","costs"].includes(kind)&&<button className="meli-primary-action min-h-11" type="submit">Aplicar filtros</button>}
  </form>
}
function ModuleContent({kind,body,sp,update,retry}:{kind:Kind;body:Payload;sp:URLSearchParams;update:(v:Record<string,string|null>)=>void;retry:()=>void}) { const rows=(kind==="costs"?body.costs:body.items)??[]; return <section aria-live="polite"><Filters kind={kind} sp={sp} update={update}/>{kind==="abc"&&<aside className="mb-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><strong>Lucro indisponível por SKU</strong><p className="mt-1">{body.profitSubset?.reason||"O contrato atual não permite atribuir lucro por produto com segurança."}</p></aside>}{kind==="finance"&&body.coverage&&<FinanceCoveragePanel coverage={body.coverage}/>} {!rows.length?<EmptyState compact title="Nenhum resultado" description={kind==="finance"?"Não há transações finais para esta loja e período.":"Não há dados para os filtros e o período selecionados."}/>:<DataTable kind={kind} rows={rows} retry={retry} connectionId={sp.get("connection_id")??""}/>} {body.page&&<nav aria-label="Paginação" className="mt-4 flex items-center justify-between gap-3"><p className="text-sm tabular-nums text-slate-500">{body.page.total==null?`${rows.length} transação(ões) nesta página`:`${body.page.total} resultado(s)`}</p><div className="flex gap-2"><button className="min-h-11 rounded-lg px-4 shadow-[inset_0_0_0_1px_rgb(203_213_225)] disabled:opacity-40" disabled={body.page.offset===0} onClick={()=>update({offset:String(Math.max(0,body.page!.offset-body.page!.limit))})}>Anterior</button><button className="min-h-11 rounded-lg px-4 shadow-[inset_0_0_0_1px_rgb(203_213_225)] disabled:opacity-40" disabled={!body.page.hasMore} onClick={()=>update({offset:String(body.page!.offset+body.page!.limit)})}>Próxima</button></div></nav>}</section> }
function FinanceCoveragePanel({coverage}:{coverage:FinanceCoverage}) { const complete=coverage.status==="complete"; const source=coverage.source==="statement_ledger"?"Extratos oficiais":coverage.source==="per_order_fallback"?"Extratos ainda incompletos":"Estrutura indisponível"; const date=(value?:string)=>value?new Intl.DateTimeFormat("pt-BR").format(new Date(value)):"—"; return <aside className={`mb-5 rounded-xl p-4 text-sm ${complete?"bg-emerald-50 text-emerald-900 shadow-[inset_0_0_0_1px_rgb(167_243_208)]":"bg-amber-50 text-amber-900 shadow-[inset_0_0_0_1px_rgb(253_230_138)]"}`} role="status"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="block">{complete?"Cobertura financeira completa":"Cobertura financeira parcial"}</strong><p className="mt-1 leading-relaxed">{complete?"A janela foi concluída pelo ledger de extratos.":"A lista contém somente transações finais já capturadas; totais ausentes não foram estimados nem convertidos em zero."}</p></div><span className="rounded-full bg-white/70 px-3 py-1 text-xs font-semibold">{source}</span></div><dl className="mt-3 grid gap-2 text-xs sm:grid-cols-3"><div><dt className="font-semibold">Janela</dt><dd>{date(coverage.from)} a {date(coverage.to)}</dd></div><div><dt className="font-semibold">Terminal</dt><dd>{coverage.terminal?"Sim":"Não"}</dd></div><div><dt className="font-semibold">Registros rejeitados</dt><dd className="tabular-nums">{coverage.rejected??0}</dd></div></dl></aside> }
function DataTable({kind,rows,retry,connectionId}:{kind:Kind;rows:Record<string,unknown>[];retry:()=>void;connectionId:string}) { const columns:Record<Kind,[string,string][]>={monitor:[["orderId","Pedido"],["occurredAt","Data"],["status","Status"],["gross","Total"],["buyerShipping","Frete comprador"],["financialStatus","Conciliação"]],finance:[["transactionId","Transação"],["occurredAt","Data"],["type","Tipo"],["orderId","Pedido relacionado"],["revenue","Receita"],["adjustment","Ajuste"]],catalog:[["title","Produto"],["sku","SKU"],["status","Status"],["price","Preço"],["availableQty","Disponível"],["updatedAt","Atualizado"]],inventory:[["title","Produto"],["sku","SKU"],["availableQty","Disponível"],["unitsSold","Vendidas"],["averagePerDay","Média/dia"],["daysRemaining","Dias restantes"]],costs:[["title","Produto"],["sku","SKU"],["cost","Custo"]],abc:[["class","Classe"],["title","Produto"],["sku","SKU"],["revenue","Receita"],["revenueShare","Participação"],["profit","Lucro"]]}; const moneyKeys=new Set(["gross","buyerShipping","sellerShipping","revenue","adjustment","profit","price","cost"]); return <div className="overflow-x-auto rounded-xl shadow-[inset_0_0_0_1px_rgb(226_232_240)]"><table className="w-full min-w-[720px] text-left text-sm"><caption className="sr-only">{config[kind].title}: resultados filtrados</caption><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{columns[kind].map(([k,l])=><th className="px-4 py-3 font-semibold" scope="col" key={k}>{l}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r,i)=><tr className="hover:bg-slate-50" key={String(r.transactionId??r.orderId??r.productId??r.id??i)}>{columns[kind].map(([k])=><td className={`px-4 py-3 ${moneyKeys.has(k)||typeof r[k]==="number"?"tabular-nums":""}`} key={k}>{kind==="costs"&&k==="cost"?<CostEditor row={r} connectionId={connectionId} onSaved={retry}/>:k==="daysRemaining"&&r[k]==null?"Sem base de venda":k==="profit"&&r[k]==null?"—":k==="revenueShare"&&r[k]!=null?`${text(r[k])}%`:moneyKeys.has(k)?moduleMoney(r[k],String(r.currency??"BRL")):k.endsWith("At")&&r[k]?new Intl.DateTimeFormat("pt-BR").format(new Date(String(r[k]))):text(r[k])}</td>)}</tr>)}</tbody></table>{kind==="costs"&&<p className="p-4 text-sm text-slate-500">Cada custo fica isolado por workspace, loja TikTok Shop e SKU. Custo desconhecido permanece “—”; zero só deve ser informado quando for um fato.</p>}{kind==="finance"&&<p className="p-4 text-sm text-slate-500">Somente campos sanitizados do ledger são exibidos. Dados pessoais e payloads brutos da TikTok Shop não fazem parte desta superfície.</p>}</div> }

function CostEditor({row,connectionId,onSaved}:{row:Record<string,unknown>;connectionId:string;onSaved:()=>void}) { const [draft,setDraft]=useState(row.cost==null?"":String(row.cost)); const [state,setState]=useState<"idle"|"saving"|"error">("idle"); useEffect(()=>{queueMicrotask(()=>setDraft(row.cost==null?"":String(row.cost)))},[row.cost]); async function save(){const cost=Number(draft);if(draft.trim()===""||!Number.isFinite(cost)||cost<0){setState("error");return}setState("saving");try{const response=await fetch(`/api/integrations/tiktok/costs?${new URLSearchParams({connection_id:connectionId})}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:row.productId,sku:row.sku??null,title:row.title,cost})});if(!response.ok)throw new Error();setState("idle");onSaved()}catch{setState("error")}} return <div className="flex min-w-48 items-center justify-end gap-2"><label className="sr-only" htmlFor={`cost-${row.id}`}>Custo de {text(row.title)}</label><input id={`cost-${row.id}`} type="number" min="0" step="0.01" inputMode="decimal" value={draft} onChange={e=>{setDraft(e.target.value);setState("idle")}} className="min-h-11 w-24 rounded-lg px-3 text-right shadow-[inset_0_0_0_1px_rgb(203_213_225)]" placeholder="—" aria-invalid={state==="error"}/><button type="button" disabled={state==="saving"} onClick={save} className="min-h-11 rounded-lg px-3 font-semibold text-sky-700 shadow-[inset_0_0_0_1px_rgb(203_213_225)] disabled:opacity-50">{state==="saving"?"Salvando…":"Salvar"}</button>{state==="error"&&<span className="sr-only" role="alert">Custo inválido ou falha ao salvar.</span>}</div> }
